trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  semver-long: '1.2.3'
  semver-med: '1.2'
  semver-short: '1'

steps:
- task: Docker@2
  displayName: Login to Quay.io
  inputs:
    command: login
    containerRegistry: quay.io
- task: Docker@2
  displayName: Build and Push
  inputs:
    repository: dad264/$(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile
    tags: |
      $(Build.SourceBranchName)-$(Build.SourceVersion)-$(Build.BuildNumber)
      $(semver-long)
      $(semver-med)
      $(semver-short)
