trigger:
  tags:
    include: 
    - v*


jobs:
- job: tag
  displayName: Tag
  # condition: and(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['gitrelease'], 'major'))
  steps:
  - bash: echo Tag that stuff
    displayName: Tag Release